application: ''
client: ''
defaultZone: http://localhost:8761/eureka/
eureka: ''
name: my-account-service
port: 8081
register-with-eureka: true
server: ''
serviceUrl: ''
spring:
  cloud:
    config:
      uri: http://localhost:8888
