info:
  component: Edge Server
 
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
    restart:
      enabled: true 

ribbon:
  eureka:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
      
server:
  port: 8888
  
spring:  boot:    admin:      client:        url: http://localhost:9999
        
zuul:
   routes:
      ecommerce-service:
         path: /**
         serviceId: ecommerce-service
         strip-prefix: false
         
ecommerce-service:
   ribbon:
      listOfServers: localhost:8080

