eureka:
  client:
    register-with-eureka: false
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ravi6706/spring-config.git
